#!/bin/bash
#SBATCH --job-name=dvars_hcpya
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=1:00:00
#SBATCH --array=0-1112
#SBATCH --output logs/hcpdev_%a
#SBATCH --constraint="intel&(haswell|broadwell|cascadelake)"

pixi run python \
	hcp.py \
	"${SLURM_ARRAY_TASK_ID}" \
	/dcs07/smart/data/human-connectome-project-openaccess/HCP1200 \
	${MYSCRATCH}/dvars/"dataset=hcpya"
