#!/bin/bash
#SBATCH --job-name=dvars_ukb
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=1:00:00
#SBATCH --array=0
#SBATCH --output dvars_ukb_%a.log
#SBATCH --constraint="intel,haswell"

module load singularity

dataset=ukb

singularity run \
  -e \
  --bind $PWD \
  --bind /dcs07/smart/data/${dataset}/rawdata \
  docker://psadil/dvars \
  python ${PWD}/${dataset}.py \
  "${SLURM_ARRAY_TASK_ID}" ${PWD}/${dataset}_srcs ${MYSCRATCH}/dvars/"dataset=${dataset}"

